Rob20.registerTable({
  "name": "Rob20.Tables.MagicItems.minorWondrousItems",
  "showplayers": false,
  "entryType": "simple",
  "entries": [
    "Feather token, anchor",
    "Universal solvent",
    "Elixir of love",
    "Unguent of timelessness",
    "Feather token, fan",
    "Dust of tracelessness",
    "Elixir of hiding",
    "Elixir of sneaking",
    "Elixir of swimming",
    "Elixir of vision",
    "Silversheen",
    "Feather token, bird",
    "Feather token, tree",
    "Feather token, swan boat",
    "Elixir of truth",
    "Feather token, whip",
    "Dust of dryness",
    "Bag of tricks, gray",
    "Hand of the mage",
    "Bracers of armor +1",
    "Cloak of resistance +1",
    "Pearl of power, 1st-level spell",
    "Phylactery of faithfulness",
    "Salve of slipperiness",
    "Elixir of fire breath",
    "Pipes of the sewers",
    "Dust of illusion",
    "Goggles of minute seeing",
    "Brooch of shielding",
    "Necklace of fireballs type I",
    "Dust of appearance",
    "Hat of disguise",
    "Pipes of sounding",
    "Efficient quiver",
    "Amulet of natural armor +1",
    "Handy haversack",
    "Horn of fog",
    "Elemental gem",
    "Robe of bones",
    "Sovereign glue",
    "Bag of holding type I",
    "Boots of elvenkind",
    "Boots of the winterlands",
    "Candle of truth",
    "Cloak of elvenkind",
    "Eyes of the eagle",
    "Scarab, golembane",
    "Necklace of fireballs type II",
    "Stone of alarm",
    "Bag of tricks, rust",
    "Bead of force",
    "Chime of opening",
    "Horseshoes of speed",
    "Rope of climbing",
    "Dust of disappearance",
    "Lens of detection",
    "Figurine of wondrous power, silver raven",
    "Amulet of health +2",
    "Bracers of armor +2",
    "Cloak of Charisma +2",
    "Cloak of resistance +2",
    "Gauntlets of ogre power",
    "Gloves of arrow snaring",
    "Gloves of Dexterity +2",
    "Headband of intellect +2",
    "Ioun stone, clear spindle",
    "Restorative ointment",
    "Marvelous pigments",
    "Pearl of power, 2nd-level spell",
    "Periapt of Wisdom +2",
    "Stone salve",
    "Necklace of fireballs type III",
    "Circlet of persuasion",
    "Slippers of spider climbing",
    "Incense of meditation",
    "Bag of holding type II",
    "Bracers of archery, lesser",
    "Ioun stone, dusty rose prism",
    "Helm of comprehend languages and read magic",
    "Vest of escape",
    "Eversmoking bottle",
    "Sustaining spoon",
    "Necklace of fireballs type IV",
    "Boots of striding and springing",
    "Wind fan",
    "Necklace of fireballs type V",
    "Amulet of mighty fists +1",
    "Horseshoes of a zephyr",
    "Pipes of haunting",
    "Gloves of swimming and climbing",
    "Bag of tricks, tan",
    "Circlet of blasting, minor",
    "Horn of goodness/evil",
    "Shrouds of disintegration",
    "Robe of useful items",
    "Boat, folding",
    "Cloak of the manta ray",
    "Bottle of air",
    "Bag of holding type III",
    "Periapt of health"
  ]
});

Rob20.registerTable({
  "name": "Rob20.Tables.MagicItems.mediumWondrousItems",
  "showplayers": false,
  "entryType": "simple",
  "entries": [
    "Boots of levitation",
    "Harp of charming",
    "Amulet of natural armor +2",
    "Golem manual, flesh",
    "Hand of glory",
    "Ioun stone, deep red sphere",
    "Ioun stone, incandescent blue sphere",
    "Ioun stone, pale blue rhomboid",
    "Ioun stone, pink and green sphere",
    "Ioun stone, pink rhomboid",
    "Ioun stone, scarlet and blue sphere",
    "Deck of illusions",
    "Necklace of fireballs type VI",
    "Candle of invocation",
    "Necklace of fireballs type VII",
    "Bracers of armor +3",
    "Cloak of resistance +3",
    "Decanter of endless water",
    "Necklace of adaptation",
    "Pearl of power, 3rd-level spell",
    "Figurine of wondrous power, serpentine owl",
    "Strand of prayer beads, lesser",
    "Bag of holding type IV",
    "Figurine of wondrous power, bronze griffon",
    "Figurine of wondrous power, ebony fly",
    "Glove of storing",
    "Ioun stone, dark blue rhomboid",
    "Stone horse, courser",
    "Vestment, druid’s",
    "Cape of the mountebank",
    "Phylactery of undead turning",
    "Gauntlet of rust",
    "Boots of speed",
    "Goggles of night",
    "Golem manual, clay",
    "Medallion of thoughts",
    "Pipes of pain",
    "Blessed book",
    "Belt, monk’s",
    "Gem of brightness ([[d50]] charges)",
    "Lyre of building",
    "Cloak of arachnida",
    "Stone horse, destrier",
    "Belt of dwarvenkind",
    "Periapt of wound closure",
    "Horn of the tritons",
    "Pearl of the sirines",
    "Figurine of wondrous power, onyx dog",
    "Amulet of health +4",
    "Belt of giant Strength +4",
    "Boots, winged",
    "Bracers of armor +4",
    "Cloak of Charisma +4",
    "Cloak of resistance +4",
    "Gloves of Dexterity +4",
    "Headband of intellect +4",
    "Pearl of power, 4th-level spell",
    "Periapt of Wisdom +4",
    "Scabbard of keen edges",
    "Figurine of wondrous power, golden lions",
    "Chime of interruption",
    "Broom of flying",
    "Figurine of wondrous power, marble elephant",
    "Amulet of natural armor +3",
    "Ioun stone, iridescent spindle",
    "Bracelet of friends",
    "Carpet of flying, 5 ft. by 5 ft.",
    "Horn of blasting",
    "Ioun stone, pale lavender ellipsoid",
    "Ioun stone, pearly white spindle",
    "Portable hole",
    "Stone of good luck (luckstone)",
    "Figurine of wondrous power, ivory goats",
    "Rope of entanglement",
    "Golem manual, stone",
    "Mask of the skull",
    "Mattock of the titans",
    "Circlet of blasting, major",
    "Amulet of mighty fists +2",
    "Cloak of displacement, minor",
    "Helm of underwater action",
    "Bracers of archery, greater",
    "Bracers of armor +5",
    "Cloak of resistance +5",
    "Eyes of doom",
    "Pearl of power, 5th-level spell",
    "Maul of the titans",
    "Strand of prayer beads",
    "Cloak of the bat",
    "Iron bands of binding",
    "Cube of frost resistance",
    "Helm of telepathy",
    "Periapt of proof against poison",
    "Robe of scintillating colors",
    "Manual of bodily health +1",
    "Manual of gainful exercise +1",
    "Manual of quickness of action +1",
    "Tome of clear thought +1",
    "Tome of leadership and influence +1",
    "Tome of understanding +1"
  ]
});

Rob20.registerTable({
  "name": "Rob20.Tables.MagicItems.majorWondrousItems",
  "showplayers": false,
  "entryType": "simple",
  "entries": [
    "Dimensional shackles",
    "Figurine of wondrous power, obsidian steed",
    "Drums of panic",
    "Ioun stone, orange",
    "Ioun stone, pale green prism",
    "Lantern of revealing",
    "Robe of blending",
    "Amulet of natural armor +4",
    "Amulet of proof against detection and location",
    "Carpet of flying, 5 ft. by 10 ft.",
    "Golem manual, iron",
    "Amulet of health +6",
    "Belt of giant Strength +6",
    "Bracers of armor +6",
    "Cloak of Charisma +6",
    "Gloves of Dexterity +6",
    "Headband of intellect +6",
    "Ioun stone, vibrant purple prism",
    "Pearl of power, 6th-level spell",
    "Periapt of Wisdom +6",
    "Scarab of protection",
    "Ioun stone, lavender and green ellipsoid",
    "Ring gates",
    "Crystal ball",
    "Golem manual, greater stone",
    "Orb of storms",
    "Boots of teleportation",
    "Bracers of armor +7",
    "Pearl of power, 7th-level spell",
    "Amulet of natural armor +5",
    "Cloak of displacement, major",
    "Crystal ball with see invisibility",
    "Horn of Valhalla",
    "Crystal ball with detect thoughts",
    "Carpet of flying, 6 ft. by 9 ft.",
    "Amulet of mighty fists +3",
    "Wings of flying",
    "Cloak of etherealness",
    "Instant fortress",
    "Manual of bodily health +2",
    "Manual of gainful exercise +2",
    "Manual of quickness of action +2",
    "Tome of clear thought +2",
    "Tome of leadership and influence +2",
    "Tome of understanding +2",
    "Eyes of charming",
    "Robe of stars",
    "Carpet of flying, 10 ft. by 10 ft.",
    "Darkskull",
    "Cube of force",
    "Bracers of armor +8",
    "Pearl of power, 8th-level spell",
    "Crystal ball with telepathy",
    "Horn of blasting, greater",
    "Pearl of power, two spells",
    "Helm of teleportation",
    "Gem of seeing",
    "Robe of the archmagi",
    "Mantle of faith",
    "Crystal ball with true seeing",
    "Pearl of power, 9th-level spell",
    "Well of many worlds",
    "Manual of bodily health +3",
    "Manual of gainful exercise +3",
    "Manual of quickness of action +3",
    "Tome of clear thought +3",
    "Tome of leadership and influence +3",
    "Tome of understanding +3",
    "Apparatus of the crab",
    "Mantle of spell resistance",
    "Mirror of opposition",
    "Strand of prayer beads, greater",
    "Amulet of mighty fists +4",
    "Eyes of petrification",
    "Bowl of commanding water elementals",
    "Brazier of commanding fire elementals",
    "Censer of controlling air elementals",
    "Stone of controlling earth elementals",
    "Manual of bodily health +4",
    "Manual of gainful exercise +4",
    "Manual of quickness of action +4",
    "Tome of clear thought +4",
    "Tome of leadership and influence +4",
    "Tome of understanding +4",
    "Amulet of the planes",
    "Robe of eyes",
    "Helm of brilliance",
    "Manual of bodily health +5",
    "Manual of gainful exercise +5",
    "Manual of quickness of action +5",
    "Tome of clear thought +5",
    "Tome of leadership and influence +5",
    "Tome of understanding +5",
    "Efreeti bottle",
    "Amulet of mighty fists +5",
    "Chaos diamond",
    "Cubic gate",
    "Iron flask",
    "Mirror of mental prowess",
    "Mirror of life trapping"
  ]
});


